const fs = require("fs");
const path = require("path");
const hre = require("hardhat");

async function main() {
  const { ethers } = hre;
  const [deployer] = await ethers.getSigners();

  const fundingGoal = ethers.parseEther(process.env.FUNDING_GOAL_ETH || "10");
  const fundingDuration = Number(process.env.FUNDING_DURATION_SECONDS || 7 * 24 * 60 * 60);
  const tokenRate = BigInt(process.env.TOKEN_RATE || "1000");
  const faucetClaimAmount = ethers.parseEther(process.env.FAUCET_CLAIM_AMOUNT || "25");

  console.log("Deploying with account:", deployer.address);
  console.log("Account balance:", ethers.formatEther(await ethers.provider.getBalance(deployer.address)), "ETH");

  const CommunityToken = await ethers.getContractFactory("CommunityToken");
  const token = await CommunityToken.deploy(deployer.address);
  await token.waitForDeployment();

  const CommunityDAICO = await ethers.getContractFactory("CommunityDAICO");
  const daico = await CommunityDAICO.deploy(
    await token.getAddress(),
    fundingGoal,
    fundingDuration,
    tokenRate,
    faucetClaimAmount
  );
  await daico.waitForDeployment();

  await (await token.setMinter(await daico.getAddress())).wait();

  const tokenAddress = await token.getAddress();
  const daicoAddress = await daico.getAddress();

  console.log("CommunityToken:", tokenAddress);
  console.log("CommunityDAICO:", daicoAddress);
  console.log("Funding goal:", ethers.formatEther(fundingGoal), "ETH");
  console.log("Funding duration:", fundingDuration, "seconds");
  console.log("Token rate:", tokenRate.toString(), "CFT per ETH");
  console.log("Faucet claim amount:", ethers.formatEther(faucetClaimAmount), "CFT");

  await writeFrontendContracts({
    networkName: hre.network.name,
    chainId: (await ethers.provider.getNetwork()).chainId.toString(),
    tokenAddress,
    daicoAddress
  });
}

async function writeFrontendContracts({ networkName, chainId, tokenAddress, daicoAddress }) {
  const tokenArtifact = await hre.artifacts.readArtifact("CommunityToken");
  const daicoArtifact = await hre.artifacts.readArtifact("CommunityDAICO");

  const outputPath = path.join(__dirname, "..", "frontend", "src", "contracts.js");
  const content = `// Auto-generated by scripts/deploy.js. Re-run deployment after resetting the local chain.
export const NETWORK_NAME = ${JSON.stringify(networkName)};
export const HARDHAT_CHAIN_ID = "0x7a69";
export const DEPLOYED_CHAIN_ID = ${JSON.stringify(chainId)};

export const CONTRACT_ADDRESSES = {
  token: ${JSON.stringify(tokenAddress)},
  daico: ${JSON.stringify(daicoAddress)}
};

export const TOKEN_ABI = ${JSON.stringify(tokenArtifact.abi, null, 2)};

export const DAICO_ABI = ${JSON.stringify(daicoArtifact.abi, null, 2)};
`;

  fs.writeFileSync(outputPath, content);
  console.log("Frontend contract config written to:", outputPath);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
